### PR TITLE
KNIME-2010: Expose useMolBlockWedging flag in RDKit 2D Depiction Preferences

### PR DESCRIPTION
**Pull request by manuelschwarze**
Since the latest RDKit release exposes property pickle flags and reapplyMolBlockWedging() functionality, we can expose to KNIME the functionality which has been available in the JS renderer for a long time, i.e. the ability to visualize bond wedging exactly as it was specified by the suer when rendering from a molblock. Nothing changes for rendering from SMILES, since SMILES does not carry bond wedging information.

For backwards compatibility by default g_bUseMolBlockWedging is set to false, but in Novartis settings we will set it to true.

Changes will also be cherry-picked into master for KNIME 5.3.

This PR was authored by @ptosco. Thanks a lot, Paolo!

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
I think the phrasing "native molblock wedging" won't make sense to most users and is difficult to explain. I would suggest just saying "wedging from the mol block" in anyhting that the user can see.

**Comment by ptosco** [comment]
> I think the phrasing "native molblock wedging" won't make sense to most users and is difficult to explain. I would suggest just saying "wedging from the mol block" in anyhting that the user can see.

@greglandrum I'll change the wording, thanks for reviewing!

**Comment by greglandrum** [comment]
I asked @ptosco about the need for new binaries with this PR and he let me know that these are built from a patched version of the RDKit code, not from an actual RDKit release.

I am not comfortable releasing RDKit binaries that do not correspond to a real RDKit release, so I can't approve this at the moment. Once Paolo's changes are in the RDKit itself, we've done the 2024.03.6 release (scheduled for late August), and the corresponding binaries have been attached to this PR, I'm happy to reconsider it.

For now I'm going to close this PR.

**Comment by manuelschwarze** [comment]
Hi Greg, Paolo's RDKit build is not necessary to get this wedging bond changes to work, which we require for our users at Novartis. It would have been the right way to do, but I totally understand that an unofficial binaries is not desired. I would propose, that we implement Paolo's changes without them (it's possible without too much effort), and later we improve this when new official binaries are available. We will update this PR shortly and reopen it...

**Comment by manuelschwarze** [comment]
Hi @greglandrum, I pushed the changes that you requested, no binaries update, no JARs update, only functionality updates. We should be fine now. Somebody who would use the default setting for the wedging bond, should not notice any difference. For Novartis, we will switch the wedging bond setting on, and are in sync with all other systems that use RDKit rendering through JS.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks for the responsiveness to my concerns!

**Comment by manuelschwarze** [comment]
I had the same concerns. But Paolo talked me out of it. Was not successful with you. :-)

**Comment by greglandrum** [comment]
> I had the same concerns. But Paolo talked me out of it. Was not successful with you. :-)

As you well know, I can also be very stubborn and picky. 😉

**Pull request merged**
