### PR TITLE
KNIME-1497: Allow strict parsing flag control

### PR DESCRIPTION
**Pull request by manuelschwarze**
NIBR is using MarvinJS sketcher to produce many SDF files. There are certain violations of the official MDL standard introduced by this and other tools, and RDKit by default is very strict in parsing SDF structures. Hence, users run from time to time into failures. There is a flag in RDKit methods that allows to control how strict the parsing should be done. We should investigate where this may have a good influence to control this flag.

My investigation has shown that it makes sense to use in the following scenarios:

* Auto-conversion: All RDKit nodes automatically turn SMILES or SDF structures into RDKit molecules. The user cannot control this in the moment. We should add a preference about strict parsing handling for this case.
* Rendering: The RDKit 2D Depiction rendering takes also plain SDF values and renders them after conversion into RDKit molecules. The user cannot control the conversion in the moment. We should add a preference about strict parsing handling for this case.
* Node Settings: Currently only 2 nodes could make use of the strict parsing setting: The RDKit from Molecule node (for converting SDF molecules) and the RDKit R Group Decomposition node (for reading cores in SDF format). In the moment it always uses the strict parsing option. We should add a node setting to control this. The default for old existing nodes should always be true. For new nodes the default could be controlled by a preference about strict parsing handling for this case. In any case the user should be able to control the setting within the node settings. As it makes only sense for handling SDF we should disable it for all other molecule types.

@greglandrum, what default settings would you suggest for these 3 cases? In the moment I have set them very conservatively to "true", which matches the old way of doing things with strict parsing. For NIBR, @ptosco and I think that it would make sense to ease things up and to set them all to false (no strict parsing). In any case, I implemented it so that old nodes behave as before.

### CODE REVIEW

**Comment by manuelschwarze** [comment]
I prepared the PR against a KNIME 4.6 version (nightly_pre4.7) which we use at NIBR, but I am intending to merge it also with master and then include it in releases for KNIME 4.2 - 4.7 as it includes important bugfixes.

**Comment by manuelschwarze** [comment]
Hmm, I just realize that there are tons of commits included here from the last years... I think the reason is that I was on master_nibr when starting that branch. Please review anyway, but I may recreate that branch based on nightly_pre4.7. Any thoughts?

**Comment by greglandrum** [comment]
> Hmm, I just realize that there are tons of commits included here from the last years... I think the reason is that I was on master_nibr when starting that branch. Please review anyway, but I may recreate that branch based on nightly_pre4.7. Any thoughts?

When we merge this all of the commits will be squashed into one, so everything should be fine.

**Comment by greglandrum** [comment]
> @greglandrum, what default settings would you suggest for these 3 cases? In the moment I have set them very conservatively to "true", which matches the old way of doing things with strict parsing. For NIBR, @ptosco and I think that it would make sense to ease things up and to set them all to false (no strict parsing). In any case, I implemented it so that old nodes behave as before.

Under most circumstances I think it's a terrible mistake to allow bad input to be accepted by default. This just leads to bad data never being fixed and, often, misleading results. So I would strongly encourage you to NOT set "strict parsing" to false by default for your internal use cases.

My answer is different for the renderer, where the idea is to show what's in the cell. In this case I think it definitely makes sense to have the strict parsing set to false by default (but to be able to change that). We could even discuss disabling sanitization and H removal for the renderer (though this leads to a different problem where the renderer is not showing the molecule that the RDKit is actually working with... we'll need to discuss that).

Based on other conversations with @ptosco, I think the major problem here is likely when query structures come in from the sketcher (like for the R group decomposition). In these cases, where you know that you're dealing with queries, I think it is perfectly reasonable to have the strict parsing argument set to false by default.

**Comment by manuelschwarze** [comment]
Thanks, @greglandrum, for your thoughts. I agree and will set next week the following preference strict parsing defaults:
- Auto-conversion: True
- Rendering: False (different than before)
- Node Settings: True
The node settings default influences all (just 2) nodes the same way, I would assume that most users leave it like that as default for the same reasons as we do. But everybody of course has now the possibility to change this setting individually in each of the 2 nodes and that is the major improvement. I think, it is good enough for the R-Group Decomposition node to just do the one additional click to disable Strict Parsing if you are using query structures as core definition and want more flexibility.

**Comment by manuelschwarze** [comment]
Done. @greglandrum, please approve the merge. I am wondering, if I should bump the version number from 4.6.1 to 4.6.2 as it is a change more than just a little bugfix. 4.7 is already taken by the KNIME 4.7 version, therefore - if we do a bump at all - we can only do a minor one. What do you think?

**Comment by greglandrum** [comment]
@manuelschwarze I think it's not necessary to do a version bump for this, but won't argue if you want to do one.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@manuelschwarze this now has a conflict that needs to be resolved before it can be merged

**Pull request merged**
