### PR TITLE
update binaries for rdkit 2021.03.1 release

### PR DESCRIPTION
**Pull request by greglandrum**
This updates the rdkit jars and binaries to reflect the 2021.03.1 release.
It looks like a lot of changes, but these are mostly changes to the test flows.
I've tested on linux and confirmed that the tests pass and everything looks good, but it wouldn't be a bad idea to also try on at least windows. @manuelschwarze : can you do that?

FYI: the updated test flows were saved with KNIME 4.2.x

I haven't bumped the version number of the extension itself since we just did that.

@sroughley: this includes your changes to the RDKit's exceptions. These cause things to look different on the Java side and lead to me having to update a lot of the test workflows. You'll probably need to update stuff on your side too.

### CODE REVIEW

**Comment by sroughley** [comment]
When you say "look different"... I assume that now `#getMessage()` works and `#what()` and `#message()` don't?  I'll check, but I'm pretty sure my exception handler workaround will fall back through to `#getMessage()` if the others fail... But I will use the simpler handling in future

**Comment by greglandrum** [comment]
The failures I had to fix were all connected with updating the expected warnings from nodes in the test flows

**Comment by manuelschwarze** [comment]
I tested on **Windows** with KNIME 4.3 Target Platform in Eclipse and found all tests working except the testsForAddConformers.addConformersDefaultTests.assertions_off

junit.framework.AssertionFailedError: Node 'RDKit SDF Difference Checker 0:86' is not executed. Error message is: Execute failed: 10 rows with differences found, e.g. Difference found in row Row889 (table 1) and row Row889 (table 2): '0.2793' is different from '1.1682'.
	at org.knime.testing.core.ng.WorkflowExecuteTest.checkNodeExecutionStatus(WorkflowExecuteTest.java:230)
	at org.knime.testing.core.ng.WorkflowExecuteTest.checkExecutionStatus(WorkflowExecuteTest.java:216)
	at org.knime.testing.core.ng.WorkflowExecuteTest.run(WorkflowExecuteTest.java:170)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)
	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:368)
	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:271)
	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:243)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:190)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I guess that is the same issue I am seeing since a long time also sometimes on our NIBR Jenkins Linux builds - sometimes that test works, sometimes it fails. @greglandrum, could you please have a look how to fix this for good? You know best what to change, so that the nodes functionality is still tested, but always working in the same way. I hope this is possible.

**Comment by manuelschwarze** [comment]
I tested now also on MacOS (Catalina, 10.15.7) with KNIME 4.3 Target Platform running in Eclipse SDK, and I get the same test results as on Windows. This includes the same error, just with a slightly different error message due to other non-deterministic conformer values:

junit.framework.AssertionFailedError: Node 'RDKit SDF Difference Checker 0:86' is not executed. Error message is: Execute failed: 11 rows with differences found, e.g. Difference found in row Row501 (table 1) and row Row501 (table 2): '1.6591' is different from '0.9506'.
	at org.knime.testing.core.ng.WorkflowExecuteTest.checkNodeExecutionStatus(WorkflowExecuteTest.java:230)
	at org.knime.testing.core.ng.WorkflowExecuteTest.checkExecutionStatus(WorkflowExecuteTest.java:216)

**Review by manuelschwarze — APPROVED** [review]
I am approving even if there is a test failure. But since it is not new, I think you can merge it. But as mentioned it would be great if you have an idea to get rid of this error for good. It is hunting us since years and is quite annoying, because it blocks our nightly build when it happens.

**Comment by sroughley** [comment]
> I tested now also on MacOS (Catalina, 10.15.7) with KNIME 4.3 Target Platform running in Eclipse SDK, and I get the same test results as on Windows. This includes the same error, just with a slightly different error message due to other non-deterministic conformer values:
> 

It would be really good to get this error fixed, it does our templated conformer generation node too

**Comment by greglandrum** [comment]
@manuelschwarze : I'm not sure what's going on there. There really shouldn't be differences between OSs if the random seed is being set properly. For example, I just generated conformers for a molecule on my linux box with an intel processor and on my mac with the Apple M1 processor and got exactly the same results (out to the fourth decimal point, which is what you need for a mol block).

I will try to make some time to go through the way the KNIME node is calling into the RDKit backend, but the problem shouldn't be in the backend itself.

**Comment by sroughley** [comment]
> I will try to make some time to go through the way the KNIME node is calling into the RDKit backend, but the problem shouldn't be in the backend itself.

that would be interesting to see if you find anything in your node.  Our templated conformer generation node has similar issues with different output between running tests locally (W10) and on the community build server (Linux)

**Comment by sroughley** [comment]
Do you plan to push this to stable releases soon?

I noticed we have some nightly test case failures (e.g. `Wrong value in row 'Row1_Transform1_0' and column 'Transformed Molecule': expected 'FC(C1:C:C:C:C:C:1Cl)C1:C:C:C:C:C:1Br', got 'FC(C1=CC=CC=C1Cl)C1=CC=CC=C1Br' (using checker 'Equality Checker'` which I assume relates to some sort of change in the SMILES writing?

I assume this particular behavior is a result of the fix to https://github.com/rdkit/rdkit/issues/2788 ?

Thanks

Steve

**Comment by greglandrum** [comment]
yeah, it should not have been writing those aromatic bonds when told to write kekule SMILES

**Comment by sroughley** [comment]
All sorted now - the other gotcha I had was my manual SVG-kludge-fix for my rendering.  As the SVG output has changed significantly, my regexes (regices?!) broke.  Thankfully, the new rendering code means I don't need the fix at all :-)

**Pull request merged**
