### PR TITLE
update rdkit binaries for the new release

### PR DESCRIPTION
**Pull request by greglandrum**
tested with:
- KNIME 4.2 on windows.
- KNIME 4.2 and the nightly on linux

### CODE REVIEW

**Comment by greglandrum** [comment]
@sroughley you may also want to be aware of this

**Comment by sroughley** [comment]
> 
> 
> @sroughley you may also want to be aware of this

Thanks @greglandrum  - I was waiting for this to happen! Will let you know if it triggers any problems downstream...

**Comment by manuelschwarze** [comment]
I noticed that the committed Linux binaries are significantly smaller than the old version, while Mac and Windows binaries increased in its size. Is there a good reason for that? I did not test them yet...

Would it be feasible to get the new binaries also into 3.7, 4.0 and 4.1, once we find them working on all operating systems with KNIME 4.2?

**Comment by greglandrum** [comment]
On testing: I've run the tests through on both windows and linux and things look fine. But you definitely should confirm that for yourself too before you deploy anywhere. Since you aren't going to deploy this version internally anyway, does that need to happen before we merge to master? The advantage of doing that is that we could then see what the community jenkins builds pick up.

@manuelschwarze The question about the file size is an interesting one and I don't have a real answer.
It looks like the anomaly was actually the last two commits of the linux file. Previously it used to be around 15MB:
https://github.com/rdkit/knime-rdkit/blob/aeb1cab803ef0c2bf99b557c4474aed2d3d3e94b/org.rdkit.knime.bin.linux.x86_64/os/linux/x86_64/libGraphMolWrap.so

> Would it be feasible to get the new binaries also into 3.7, 4.0 and 4.1, once we find them working on all operating systems with KNIME 4.2?

My enthusiasm for that is limited since it's a non-zero amount of work. You need a 3.7 version, right?

**Comment by sroughley** [comment]
We dont need 3.7, but 4.1 would be "kind of" useful... We are trying to move away from 3.7/4.0 support at Vernalis (see https://forum.knime.com/t/vernalis-plans-to-no-longer-support-knime-3-7/28142?u=vernalis if you really dont want us to!)

**Comment by manuelschwarze** [comment]
@greglandrum we are planning at some point anyway to move to KNIME 4.2, just in the moment everything is on hold. The question for me to decide about 3.7 support would be, if it would really make a difference to our NIBR scientists? Are there very important bug fixes included that everybody just needs to have? Feature-wise, we did not do any changes on the nodes' side, hence I guess the 3.7 users would not care for the moment about new features of RDKit itself... 
In general, you are right, we do not have to wait for my own testing. The changes from Java / config side are minimal, from what I can tell. I would approve to merge into master.

**Comment by greglandrum** [comment]
@manuelschwarze there have been a lot of changes, and some of them will be visible in KNIME without needing to modify the nodes. For example, the molecule rendering has gotten a ton better.

**Comment by greglandrum** [comment]
@sroughley : I can do a backport to 4.1

**Comment by greglandrum** [comment]
I'm converting this as a draft because I think I just saw some alarming behavior while using the linux version.
I'm going to do a clean build from eclipse and try it out a bit to convince myself that everything's ok, then reopen this

**Comment by manuelschwarze** [comment]
Thanks for pointing out the improvements. If there is a chance to get it also for 3.7, that would be great. I need to do a minor update (NIBR plugin) anyway in the next few weeks, so I could easily sneak in the RDKit nodes updates as well. Thanks for the extra effort in advance. You suggested in summer to create a nightly_pre4.2 branch, which I could use to sync my NIBR master with - I think that would make sense for everybody who needs the code before breaking changes of KNIME 4.2.

**Comment by greglandrum** [comment]
@manuelschwarze I rebuilt the linux binary (just in case) and repeated the tests a few times to make sure things are ok. As far as I can tell everything looks good now.
I also made some efficiency changes to the `Add Conformers` node that might also help with potential memory problems.

**Comment by greglandrum** [comment]
Ok, this change is merged and the previous state of master is now here: https://github.com/rdkit/knime-rdkit/tree/nightly_pre4.2

**Comment by greglandrum** [comment]
@manuelschwarze @sroughley I just updated the binaries on the nightly_pre4.2 branch. I don't think we can actually do nightlies for those any more, but it certainly would be possible to update the 3.7 and 4.1 release branches
Still, seems like some testing should probably be done there first

**Comment by sroughley** [comment]
Could you bump the version so I can set a new lower bound to catch the change from `#message()` to `#what()` (why?!) for the exceptions? Thanks!

**Comment by manuelschwarze** [comment]
@greglandrum When you say we cannot do nightlies you simply refer to the fact that this branch is not included in the regular nightly build run like the master branch, I guess. Correct? I do not think that will be a big issue, if we include the main changes into the 3.7 and 4.1 branches as you suggested. I am currently ooo and will be back working on November 2 and will reserve some time for that week to test it in my KNIME 3.7 setup - could you please send me the branch I should test with?

**Pull request merged**
