### PR TITLE
New/rgroup decomposition

### PR DESCRIPTION
**Pull request by manuelschwarze**
Performs an R-Group decomposition for an input RDKit Mol column. The algorithm in RDKit was developed in 2018/2019.  It is still in beta state and should be used with care. Results may vary in later versions.

### CODE REVIEW

**Comment by manuelschwarze** [comment]
@greglandrum , I am wondering what we should do with the version number when merging this into the master...  Also, I would like to try out the new RDKit binaries with the code. Is there a realistic timeline you can give me?

**Comment by greglandrum** [comment]
@manuelschwarze: this branch has the new binaries and some updated tests:
https://github.com/rdkit/knime-rdkit/tree/dev/update_rdkit_binary

I still need to bump the version on that and I want to run the tests through on linux again before doing the PR, but you can definitely take a look at it.

**Comment by greglandrum** [comment]
I tried to run this in 3.7 on linux and I get the following exception when I try to open the test workflow or add the new node to an existing workflow:
```
java.lang.NoClassDefFoundError: Could not initialize class org.rdkit.knime.nodes.rgroupdecomposition.Labels
	at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeDialog.createLabelsModel(RDKitRGroupDecompositionNodeDialog.java:264)
	at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeModel.<init>(RDKitRGroupDecompositionNodeModel.java:163)
	at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeFactory.createNodeModel(RDKitRGroupDecompositionNodeFactory.java:73)
	at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeFactory.createNodeModel(RDKitRGroupDecompositionNodeFactory.java:1)
	at org.knime.core.node.NodeFactory.callCreateNodeModel(NodeFactory.java:481)
	at org.knime.core.node.Node.<init>(Node.java:264)
	at org.knime.core.node.Node.<init>(Node.java:254)
	at org.knime.core.node.workflow.FileNativeNodeContainerPersistor.preLoadNodeContainer(FileNativeNodeContainerPersistor.java:208)
	at org.knime.core.node.workflow.FileWorkflowPersistor.loadNodeContainer(FileWorkflowPersistor.java:943)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7817)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7708)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7662)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7583)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7556)
	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7401)
	at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:175)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by manuelschwarze** [comment]
I guess you are using the new binaries already? (That could explain it, if something changed how the RDKitLabel class works.)

-Manuel

Sent from my iPhone

Am 01.11.2019 um 03:48 schrieb Greg Landrum <notifications@github.com<mailto:notifications@github.com>>:


I tried to run this in 3.7 on linux and I get the following exception when I try to open the test workflow or add the new node to an existing workflow:

java.lang.NoClassDefFoundError: Could not initialize class org.rdkit.knime.nodes.rgroupdecomposition.Labels
        at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeDialog.createLabelsModel(RDKitRGroupDecompositionNodeDialog.java:264)
        at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeModel.<init>(RDKitRGroupDecompositionNodeModel.java:163)
        at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeFactory.createNodeModel(RDKitRGroupDecompositionNodeFactory.java:73)
        at org.rdkit.knime.nodes.rgroupdecomposition.RDKitRGroupDecompositionNodeFactory.createNodeModel(RDKitRGroupDecompositionNodeFactory.java:1)
        at org.knime.core.node.NodeFactory.callCreateNodeModel(NodeFactory.java:481)
        at org.knime.core.node.Node.<init>(Node.java:264)
        at org.knime.core.node.Node.<init>(Node.java:254)
        at org.knime.core.node.workflow.FileNativeNodeContainerPersistor.preLoadNodeContainer(FileNativeNodeContainerPersistor.java:208)
        at org.knime.core.node.workflow.FileWorkflowPersistor.loadNodeContainer(FileWorkflowPersistor.java:943)
        at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7817)
        at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7708)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7662)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7583)
        at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7556)
        at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7401)
        at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:175)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by greglandrum** [comment]
@manuelschwarze: No, I was using this branch, so it shouldn't have been using the new binaries.
Have you tried this on linux?

**Comment by manuelschwarze** [comment]
I did not run this on Linux. I expected that all RDKit classes that I use work the same on Windows, Linux and Mac. That is crucial and was always the case in regards to APIs, in the past the only differences we encountered sometimes was in calculations. 
But let me try it on Linux as you suggest. Will take some time as I need to setup a new development environment on CentOS7 for that.

**Comment by greglandrum** [comment]
Yes, obviously it's critical; that's why I'm surprised that there would be a difference.

**Comment by manuelschwarze** [comment]
So, I tested on RH6 and CentOS7 and in both cases I could reproduce the buggy behavior you encountered. I also let all old automated tests run (without involving the new R Group Decomposition calls), and on both systems they worked fine. 

I am attaching a screenshot of the error I get when opening the new R Group Decomposition test workflow on Linux:
image

Since the JAR files we have are the same on all operating systems, and it is working on Windows, my conclusion is that the Linux binary (and maybe also the Mac binary) files are not matching the JAR files properly, possibly caused by last minute changes of the past. 

My suggestion for now would be to merge in the new binaries into this branch and then get it right with the JAR files. Would you please try that as you had suggested anyway in the past? 

To avoid such incompatibilities in the future the native files for all operating systems would need to be build from the exact same source (usually at the same time to really ensure this) and then they would all produce also the same JAR files as Java API - and it should not matter, which JAR files we take at the end as they would all work together with all binaries.

**Comment by greglandrum** [comment]
I'll take a look again when I'm back in the office (tomorrow) and have access to my Linux machine again

**Comment by greglandrum** [comment]
hmm, I had commented on this already this morning, but it seems like that comment vanished (or I forgot to post it... equally likely).

My normal process for doing binaries is, in fact, to use the same git tag for all three operating systems. Something odd happened with that last release.

In any case, this PR works fine with the new binaries on linux. I will take a look at the node a bit more today and merge if I don't find anything odd.

**Comment by manuelschwarze** [comment]
I have merged the latest changes from master (new RDKit binaries, consistent version bump to 4.0). Now the code should also work for you, @greglandrum, when trying it out on Linux. Could you please have a look at the tests and change them to something more minimal and still useful?
I will make the node available now already for review to our NIBR folks in our nightly build. If you think it is ready to merge already, please go ahead.
Please be aware of the following:
1. The old R Group Decomposition node is still available in the node repository and can be used (I just put "deprecated" in the name, but it should still appear for a while).
2. The new R Group Decomposition node  I named "RDKit R-Group Decomposition (new beta)" so that people know that it may still change slightly once we receive feedback from NIBR and - depending on when we merge it - also from others.
My plan would be to wait a few weeks for feedback, then implement certain changes and then really deprecate the old node and take away the "new beta" tag from the new node's name.

**Review by greglandrum — APPROVED** [review]
Looks good. I added a hand-created test as well

**Pull request merged**
