### PR TITLE
KNIME-1496,KNIME-1478 Bugfixes in rendering

### PR DESCRIPTION
**Pull request by manuelschwarze**
* Fonts of atoms are unusually large sometimes in rendered molecules. Reason is that apparently the often used MarvinJS sketcher is using a different scaling than RDKit. Before rendering a structure we can normalize it to adapt the scaling, so that the structures incl. fonts are looking good and nicely scaled. I ran into normalization failures when there are no conformers present, in that case I am skipping it now.
* Aligned missing cell representation in RDKit 2D Depicter to draw a red ? like the rest of KNIME renderers do

@ptosco, thanks for the suggestion and help.

### CODE REVIEW

**Comment by manuelschwarze** [comment]
I prepared the PR against a KNIME 4.6 version (nightly_pre4.7) which we use at NIBR, but I am intending to merge it also with master and then include it in releases for KNIME 4.2 - 4.7 as it includes important bugfixes.

**Comment by manuelschwarze** [comment]
Hmm, I just realize that there are tons of commits included here from the last years... I think the reason is that I was on master_nibr when starting that branch. Please review anyway, but I may recreate that branch based on nightly_pre4.7. Any thoughts?

**Comment by greglandrum** [comment]
> Hmm, I just realize that there are tons of commits included here from the last years... I think the reason is that I was on master_nibr when starting that branch. Please review anyway, but I may recreate that branch based on nightly_pre4.7. Any thoughts?

We squash commits when we do a PR merge, so this will only show up as one commit anyway.

**Review by greglandrum — CHANGES_REQUESTED** [review]
I don't think it is a good idea to do this work in the renderer. Aside from the additional computation which is required (slowing down the renderer), I think a renderer should show what's actually in the cell.

I agree that it can be irritating to use molecule drawings from different places due to differences in the bond lengths used, but I think the correct "KNIMEy" way to fix this would be to add a "Normalize 2D Structure" node (or something equivalent) which allows the user to be explicilty about doing this work.

**Comment by ptosco** [comment]
@greglandrum I struggle to see how a user might want to see the original drawings with huge fonts. I think a proper fix for this issue would be to fix the font scaling in RDKit, which should automatically adapt to the scale of the drawing (and apparently doesn’t). Note that the drawing is already auto-scaled to the cell size, unless `fixedScale` or `fixedBondLength` have non-default values - but the fonts don’t follow.

Until this is is done on the RDKit side, not fixing the rendering in KNIME would only cause irritation in users and require an additional step to get decent pictures, for users who realize what the additional step would be - most users would just file a bug ticket, with good reason.

To address your concern, we can expose the normalization as an Advanced setting which defaults to `true` in the Advanced settings to give users a chance to switch it off if they want to: I have already implemented the same behavior in the JS renderer.

We could do the same for coordinate canonicalization (default: no canonicalization) and `straightenDepiction()` (default: minimal).

@greglandrum What do you think?

**Comment by greglandrum** [comment]
@ptosco : it's not that users want to see things with huge fonts, it's that they want to see what's actually in the table. And, if you're working with molecules which come from multiple sources it can be very useful to see that those molecules have different standard bond lengths so that you know you need to fix that.

To repeat myself from before: I believe the purpose of the renderers in KNIME tables is to show you what is actually present in the cell. If you want to change what's actually present in the cell then KNIME has a way to let you do it.

Having said all of that: I think having an option for MolDraw2D which adjusts the font size based on the average single bond length is something that's worth thinking about.

**Comment by ptosco** [comment]
> @ptosco : it's not that users want to see things with huge fonts, it's that they want to see what's actually in the table. And, if you're working with molecules which come from multiple sources it can be very useful to see that those molecules have different standard bond lengths so that you know you need to fix that.

99% of KNIME users do not care about the source of the molecules, nor about their average bond length, nor why it is different depending on the source, and have no desire to fix that: they just want to see decent molecules, and they won’t, and hence will file a bug. Which is what, IMHO correctly, @manuelschwarze did with me.

> 
> To repeat myself from before: I believe the purpose of the renderers in KNIME tables is to show you what is actually present in the cell. If you want to change what's actually present in the cell then KNIME has a way to let you do it.

I will also repeat myself: by default RDKit already scales molecules to fit the cell size, unless drawing options are changed from their default, so strictly speaking, it is already not showing what is actually present in the cell, since original coordinates are transformed.
I consider the fact that fonts do not scale accordingly a bug.

> 
> Having said all of that: I think having an option for MolDraw2D which adjusts the font size based on the average single bond length is something that's worth thinking about.

There are other issues that I have seen with font scaling which are less straightforward to reproduce. My plan is to address them when I have some time.
In the meantime, I think we need to do something for the scaling issue that does not require additional user intervention, or we will get many, many complaints from users, with reason.

**Comment by greglandrum** [comment]
Feel free to make those modifications to your local KNIME install or to add an option for it here, which is disabled by default.

**Comment by manuelschwarze** [comment]
Thanks for the discussion, @greglandrum and @ptosco. I will add next week a preference setting to control this. It will be contained in the "RDKit 2D Depiction" preference page called "Normalize depictions", set to false by default as suggested (and also preferred by me). For NIBR we will set this to true as we have many SDF structures in our KNIME workflows originating from sketcher tools outside of KNIME or RDKit, that otherwise would show up ugly. Not everybody would use RDKit nodes all the time, many users just want to see rendered structures, til now done with Avalon Depicter, but in the near future it happens to be done with RDKit. The users would not really care, but will just complain about the result if they do not like it.

**Comment by ptosco** [comment]
@manuelschwarze Thanks Manuel, that sounds perfect! @greglandrum thanks for agreeing to the option :)

**Comment by greglandrum** [comment]
@manuelschwarze makes sense to me as well.

**Comment by manuelschwarze** [comment]
Done. @greglandrum, please approve for merging.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
