### PR TITLE
Add RDKit2SVG node

### LINKED ISSUE #71: New Node: Generating an SVG column as rendering
This node would function like the highlighting node, but without the highlighting. The new node should be streamable.

Optionally, we could provide PNG rendering as well from it (need to figure out how to do this) based on a given size.

### PR DESCRIPTION
**Pull request by greglandrum**
Adds a new node for converting RDKit molecules directly to SVG without doing highlighting or using the "Renderer to Image" node (which is slow).
This includes a bunch of options to change how the molecule is drawn.

This also bumps the version of the nodes to 4.4.0

### CODE REVIEW

**Comment by manuelschwarze** [comment]
Very nice job. You really turn now into a Java RDKit nodes developer. 
A few minor things: 
- Copyright is everywhere set to 2012, but should be 2021.
- Some code comment
- In the main factory method where you generate the SVG drawing you hand over the DrawOptions for each single drawing again and again. This cost a lot of performance. Isn't there way to generate such a DrawOptions object once and hand it always over to the Drawing object? If that is possible you would create that DrawOptions object outside of the factory functionality and mark such a variable as "final" so that you can refer to it also inside of the factory method, and you would mark that object for cleanup in that case _without_ our magic "waveid", so hat it gets only cleaned up when all rows were executed). Just a suggestion.

I did not test it, but it looks straight forward and you even got a test workflow attached. If this code is good to merge and compatible with KNIME 4.3 (is it?) it may make sense to merge it quickly and release it immediately to our NIBR users. Do you see a big risk doing that?

**Comment by greglandrum** [comment]
> Very nice job. You really turn now into a Java RDKit nodes developer.

Ha! That's pretty unlikely. :-)

> 
> * Copyright is everywhere set to 2012, but should be 2021.

Fixed

> * Some code comment

not sure what you mean. I think I've added comments for the parts which are non-obvious or where there might be questions.

> * In the main factory method where you generate the SVG drawing you hand over the DrawOptions for each single drawing again and again. This cost a lot of performance. Isn't there way to generate such a DrawOptions object once and hand it always over to the Drawing object? If that is possible you would create that DrawOptions object outside of the factory functionality and mark such a variable as "final" so that you can refer to it also inside of the factory method, and you would mark that object for cleanup in that case _without_ our magic "waveid", so hat it gets only cleaned up when all rows were executed). Just a suggestion.

I understand the suggestion, and appreciate learning how to handle this kind of situation in the future. In this case though, it's not appropriate. This call:
```
MolDrawOptions opts = molDrawing.drawOptions();
```
doesn't actually create a new object; it just returns a pointer to the drawOptions object which the molDrawing owns.

> 
> I did not test it, but it looks straight forward and you even got a test workflow attached. If this code is good to merge and compatible with KNIME 4.3 (is it?) it may make sense to merge it quickly and release it immediately to our NIBR users. Do you see a big risk doing that?

I don't see any reason why it wouldn't work with KNIME 4.3, but I can't currently run 4.3 from eclipse (there's some problem running 4.3 and 4.4 from the same workspace), so I can't test this. I also created the test workflows from inside of 4.4, so they may or may not work in 4.3
I will try and resolve the issue that doesn't allow me to work with 4.3 today and will update the test workflows if I can do that.
Otherwise I will just go ahead and merge as-is so that you can try things with 4.3.

**Comment by manuelschwarze** [comment]
We decided not to wait with your release. I would like to test this first in 4.3 and we will give users an update anyway soon again. So no rush necessary from my side. It would be better to have the test workflow being compatible for 4.3. I will add some more info to my code comment to clarify what I mean.

**Comment by greglandrum** [comment]
Given that the 4.3 code is on a branch anyway, I would propose we merge this as-is and then see about back-porting the code to the 4.3 branch when you have time to do so (or I manage to get 4.3 working again).

**Comment by manuelschwarze** [comment]
I agree, please go ahead with merging, and afterwards please save the test workflow with KNIME 4.3 so that we can open and run it without any warnings in KNIME 4.3 systems as well. I would not know actually, how to "back-port" a workflow. I hope you have a trick for that from your KNIME colleagues.

**Pull request merged**
