### PR TITLE
Update RDKit binaries to v2016_09_1

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by manuelschwarze** [comment]
The Open3DAlignment test still fails for KNIME 3.2 on Windows 64-bit and Mac 64-bit. Others OS flavours I have not tested yet.

**Comment by greglandrum** [comment]
I can confirm that I'm getting different results when generating coordinates in Python for at least one of the molecules on Linux64 (matches what's in the test) and the Mac.
Given that this is a bug in the underlying RDKit, not in the KNIME nodes, I don't think this needs to affect updating the nodes, but we do need to stop calling Generate3DCoords in this test. We can just read the final 3D coords from a file. I'll fix this and update the PR.

**Comment by greglandrum** [comment]
Those two commits allow the Open3D tests to run on both Linux64 and the Mac, hopefully they will clear up windows too.

What I did was to remove the Generate Coords node from the workflow (well, it's still there, but it's not doing anything) and replace it with a table reader that pulls in the expected 3D coordinates. This allows the test workflow to only test Open3DAlign functionality and not also be dependent on cross-platform consistency of the coordinate generation.

**Comment by manuelschwarze** [comment]
Everything is working well now in KNIME 3.2 on Win32, Win64, Lin32, Lin64 and Mac64, which I ran tests with.

**Pull request merged**
