### PR TITLE
Update RDKit binaries to v2021.09

### PR DESCRIPTION
**Pull request by greglandrum**
@manuelschwarze : this does the update of the RDKit binaries to the most recent release.

The tests all pass for me with 4.3 o

The other change is that I modified the RDKit to SVG tests and saved them with KNIME 4.3. I think at this point all the tests are written with 4.3 or older.

Since it's coming the same day as your changes went in, I'm not updating the version number.
Assuming you approve this, I would suggest that we do a release for 4.3, 4.4, and 4.5 after this is merged.

### CODE REVIEW

**Comment by manuelschwarze** [comment]
Hi @greglandrum: Thanks! I will look at it later today and run the tests for 4.3 on Windows, Linux and Mac. I am not sure, if you follow the news around log4j, but updating to 2.15.0 is not anymore the final solution to the issue, as it is still vulnerable although not as bad as before. Therefore, Dan from OPSIN updated to 2.16.0 as suggested by officials, and he plans also to do an official release with these changes and other things he worked on next week. See https://github.com/dan2097/opsin/issues/174. I would like to wait for it, then put it in the RDKit extensions for the nightly - really only a "formality", but very important to make security scanners happy. Afterwards, we should do _the_ release or at least _another_ release. It could also make sense to release now (as you suggested), and just do another one then next week. Up to you.

**Comment by greglandrum** [comment]
@manuelschwarze given the severity of the log4j thing and the fact that 2.15.0 is at least a partial fix (I guess?) maybe it makes sense to go ahead and do a release once you've approved this PR and then do the "formality" release with the new opsin jar once that's ready.

Sound good?

**Comment by manuelschwarze** [comment]
@greglandrum Yes, I fully agree. Let's do then two releases, one now, the other one maybe next week. 

I tested this one on KNIME 4.3 with the following results:

- Windows 10: Successfully done, there only the old AddConformer node tests are failing (nothing new).
- Mac OS: The AddConformer node tests are failing as well as the new SVG node tests (same as yesterday, so any changes you may have done seem not change the behavior - but there seem only differences in the output, similar to AddConformer)
- Linux (CentOS7): All tests are running through fine

From my side I think it will be fine. Please merge and release.
I am off next week, but when I get notified about OPSIN I plan to integrate the new version, so that we can do another release.

It would be helpful, if you could give some hints for the RDKit nodes users what to watch out for based on the RDKit binary changes.

**Comment by greglandrum** [comment]
Thanks @manuelschwarze, I will merge and figure out how to do the releases.
I'll also try and figure out what's going on with the SVG node failure on MacOS, I don't think that should be happening, but it's not the end of the world

Have a great break.

**Comment by greglandrum** [comment]
@manuelschwarze : I just updated the Mac binary so that it uses freetype like the linux and windows builds. This *should* fix the SVG test failures.
Do you have time to run the Mac tests again?

**Comment by manuelschwarze** [comment]
@greglandrum I just re-tested on Mac. I believe I saw two tests about SVG failing earlier today (too bad that I removed the test results file already), but now with the new build only the SVG Adapter Test workflow is delivering unexpected results. The AddConformer tests continue to fail as well.

**Pull request merged**
