### PR TITLE
Merge NIBR 2016-12-16

### PR DESCRIPTION
**Pull request by manuelschwarze**
Added new nodes RDKit Molecule Catalog Filter and RDKit Adjust Query Properties
Increased version for all RDKit plugins to 3.2.2 (aligned again)
Added JavaDocs

### CODE REVIEW

**Comment by greglandrum** [comment]
How on earth did this end up touching >1000 files?

**Comment by greglandrum** [comment]
The code review interface is going to be useless for this due to the number of changed files. I'll just make comments out here.

**Comment by greglandrum** [comment]
Suggested new first paragraph of the documentation for the Adjust Query Properties node:
```This node allows common adjustments to the matching behavior of molecules that are intended to be used as queries..```

RDKit Mol Column: `The input column with molecules to be used as queries.`

New Column Name: `The name of the new column which will contain the tuned queries as RDKit Molecules`

Remove all commas from the other argument descriptions. :-)

**Comment by greglandrum** [comment]
Molecule Catalog Filter documentation changes.

overview:
```Filters a table of molecules by applying filters taken from a set of standard catalogs. The second output table contains a very detailed view of the reasons why a molecule was filtered out. The node gives the option to generate one or more atom lists columns with the indexes of the atoms that matched the rule; this information can be used with the RDKit Molecule Highlighting node to color the associated substructures.```

Atom list handling: `controls whether or not lists of atoms matching the filters are generated. This also controls whether all matching atoms are in a single list or if there is a column per filter catalog`

**Comment by greglandrum** [comment]
The functionality of the nodes looks good and it seems like all important options are supported.
All tests pass for me.
Once the docs have been updated (if you check the changes into your branch they will automatically appear here) I will merge the PR.

**Comment by manuelschwarze** [comment]
The >1000 files are JavaDoc files that I checked in, hoping that this would be useful to have them always ready to read. You don't have to review them. There are really only the two new node packages that you found, which are the important new information to review more closely.
I will update the docs.

**Comment by manuelschwarze** [comment]
Ok, done. How can I connect the two feature request "issues" to this pull request? Does GitHub support this?

**Comment by greglandrum** [comment]
All you have to do is mention them in a comment. Just saying that this PR addresses #1 and #4 establishes the link.

I normally also mention the issue (just like I did above) in the relevant commit message; then you end up a with a direct link between the issue and the commit. If you use language like `Fixes #1` in the commit message, it will automatically close the issue when the PR is merged.

**Pull request merged**
