### PR TITLE
Fix/github22

### LINKED ISSUE #22: OptimizeGeometry node: generate warnings when no coords are present

### PR DESCRIPTION
**Pull request by greglandrum**
This fixes #22.
Note that it doesn't make sense to merge this until after #23 has been merged.

### CODE REVIEW

**Comment by manuelschwarze** [comment]
I am trying to run all regression tests on Windows 64-bit. 
I had to use a very small epsilon value to compare results of the Optimize Geometry node in the new test for github22, before it did not work because of very tiny differences (due to the OS). Now these tests runs through.
The Structure Normalizer tests are failing. The Java code has not changed for a long time, hence it must be something on the native side - here is the log that I get:
```
2017-05-12 15:40:59,241 : DEBUG : KNIME-Worker-29 : LocalNodeExecutionJob : RDKit Structure Normalizer : 8:27 : RDKit Structure Normalizer 8:27 Start execute
2017-05-12 15:40:59,247 : INFO  : KNIME-Worker-29 : RDKitStructureNormalizerNodeModel : RDKit Structure Normalizer : 8:27 : Initializing StruChk of RDKit with the following options:
StruCheck
-cc
-cs
-tm
-cl 3
-cn 999
-or
-ta "C:\Users\schwama8\AppData\Local\Temp\checkfgs5165325293148975539.trn"
-ca "C:\Users\schwama8\AppData\Local\Temp\checkfgs3156146216755507123.chk"
-l "C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer346242777917752869.log"
2017-05-12 15:40:59,247 : INFO  : KNIME-Worker-29 : RDKitStructureNormalizerNodeModel : RDKit Structure Normalizer : 8:27 : checkfgs5165325293148975539.trn copied from C:\DevelopmentGit\knime-rdkit\org.rdkit.knime.testing\regression-tests\workspace\Tests for Structure Normalizer\Structure Normalizer - Default Tests\Java Edit Variable (#59)\drop\config\checkfgs-test.trn
2017-05-12 15:40:59,247 : INFO  : KNIME-Worker-29 : RDKitStructureNormalizerNodeModel : RDKit Structure Normalizer : 8:27 : checkfgs3156146216755507123.chk copied from C:\DevelopmentGit\knime-rdkit\org.rdkit.knime.testing\regression-tests\workspace\Tests for Structure Normalizer\Structure Normalizer - Default Tests\Java Edit Variable (#59)\drop\config\checkfgs-test.chk
2017-05-12 15:40:59,255 : INFO  : KNIME-Worker-29 : AbstractRDKitNodeModel : RDKit Structure Normalizer : 8:27 : Execution of RDKitStructureNormalizerNodeModel took 14ms.
2017-05-12 15:40:59,255 : DEBUG : KNIME-Worker-29 : RDKit Structure Normalizer : RDKit Structure Normalizer : 8:27 : reset
2017-05-12 15:40:59,255 : ERROR : KNIME-Worker-29 : RDKit Structure Normalizer : RDKit Structure Normalizer : 8:27 : Execute failed: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.
2017-05-12 15:40:59,255 : DEBUG : KNIME-Worker-29 : RDKit Structure Normalizer : RDKit Structure Normalizer : 8:27 : Execute failed: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.
java.lang.Exception: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.
	at org.rdkit.knime.nodes.structurenormalizer.RDKitStructureNormalizerNodeModel.initialize(RDKitStructureNormalizerNodeModel.java:734)
	at org.rdkit.knime.nodes.structurenormalizer.RDKitStructureNormalizerNodeModel.processing(RDKitStructureNormalizerNodeModel.java:578)
	at org.rdkit.knime.nodes.AbstractRDKitNodeModel.execute(AbstractRDKitNodeModel.java:903)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:732)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:566)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1128)
	at org.knime.core.node.Node.execute(Node.java:915)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:561)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
2017-05-12 15:40:59,256 : DEBUG : KNIME-Worker-29 : WorkflowManager : RDKit Structure Normalizer : 8:27 : RDKit Structure Normalizer 8:27 doBeforePostExecution
2017-05-12 15:40:59,256 : DEBUG : KNIME-Worker-29 : NodeContainer : RDKit Structure Normalizer : 8:27 : RDKit Structure Normalizer 8:27 has new state: POSTEXECUTE
2017-05-12 15:40:59,256 : DEBUG : KNIME-Worker-29 : WorkflowManager : RDKit Structure Normalizer : 8:27 : RDKit Structure Normalizer 8:27 doAfterExecute - failure
```
Greg, do you see anything that would explain this? Any advice what to change?
Is this working fine on Mac and Linux? If so, then maybe the issue related to the build-process for Windows, and that the resulting DLL is incomplete?

**Comment by greglandrum** [comment]
On the failing test: does that test pass for you on Win64 if you run it with the current master (i.e. before you apply the PR)?

**Comment by greglandrum** [comment]
On the parameter tolerances for Optimize Geometries: which test are you talking about? and what did you have to set the epsilon to?

**Comment by greglandrum** [comment]
FWIW: the Structure normalizer test is failing for me on the Mac too if I try and run the test workflow normally. If I open the workflow and step through it, on the other hand, everything is fine.
This feels like memory corruption/use of uninitialized memory in the struchk code, which I think should be the same between this release and the last one.
I'm going to do a bit more investigation, but if this is what I think it is, then it's not a new problem it's just new that we're seeing it.

**Comment by manuelschwarze** [comment]
1. Structure Normalizer: I tested also the master, and there it fails also. This is strange because at some point it has worked. The node itself actually goes green, but that might be a bug in itself - I am only logging the init error. Hmm, when I wrote that it always worked :-). As you say there is an error message that the initialization of strucheck failed with error code 1, but it is logged only. Clueless in the moment what could be the cause... thanks for looking into it. Good that you can reproduce it on the Mac.

2. Optimize Geometry Node: The test that I changed slightly was the workflow you wrote for github22, which as expected is in the file knime-rdkit\org.rdkit.knime.testing\regression-tests\zips\Tests for Optimize Geometry.zip

**Comment by greglandrum** [comment]
I'm not sure what we should do with the structure normalizer thing.
The functionality is useful to people, but the lack of reliability of the underlying C code (not RDKit code) seems to make it poorly suited to the types of tests you're doing.

We probably need to seriously simplify that test.

**Comment by greglandrum** [comment]
What did you set the threshold to?

**Comment by manuelschwarze** [comment]
I set it only for the Energy column to 0.000001. Before doing that I got as error message:
Execute failed: Wrong lower bound in column 'Energy': expected '167.56297049484607', got '167.56296988458521'

**Comment by greglandrum** [comment]
hmm, that's clearly down in the roundoff error.
I will simplify and go with 0.0001

**Comment by greglandrum** [comment]
Ah, I see, you added the change already
I'm going to replace that with the looser 0.0001 tolerance

**Comment by manuelschwarze** [comment]
I played a little more now with the node, and it is indeed some raise condition. Often it works, sometimes it does not. Without changing any Java code or node settings. Pretty bad. My code catches such a failure correctly and lets the node fail in that situation. So, everything is correct from my side except the underlying native C code. I am having already a global lock, so that only one thread deals with StruCheck at a time. Did something change recently in the native code? When I wrote the node originally, I am very sure I would have noticed such fuzzy behavior, so in my opinion there was a time when it always worked.

I would suggest to take out the Structure Normalizer test ZIP from the zips folder and put it only into the manual-test-zips folder, which contains the non-automated tests, which we rarely run to be honest. If somebody fixes the C code level, we can move it back. If you agree, please move the file.

**Comment by greglandrum** [comment]
ok, super simplified test is checked in, see what you think

**Comment by greglandrum** [comment]
Take a look at the simple test I just checked In, which only uses the defaults and works for me on the Mac. If that works for you too we can go with this and then turn the real tests back on if/when the C code is fixed

**Comment by manuelschwarze** [comment]
I had a look at the test, but it looks pretty much the same to me. Did you check the correct one in?
The automated tests are still failing, also with the new checked-in file. I don't think it has anything to do with complexity, since if I just run a simple node it often fails, regardless of the workflow around. 

I manipulated my code for testing by surrounding the failing init code with a loop that retries for 10 times after sleeping 500 millis. In the Eclipse console I am seeing at the very end what was written out to the syserr stream by StruCheck - this is some more detail why StruCheck failed. Maybe it gives you a hint. To me it looks like some code screws up the option string before it is passed to StruCheck. 

```
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer8273642489034574843.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7383288596190592973.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer1632011738777406578.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3397684235037407199.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer87091434802595951811.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer83400329535055269181.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer11282252784302641081.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer84395531427146293941.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer49381136250385306121.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer50489055535149236131.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer83247545454007504821.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer39806462529835123901.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer2706428750211991505.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer2706428750211991505.log
'
Illegal option 'S' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer2706428750211991505.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer109802572757191294.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option 'p' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer4259037362833443311.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option ',O' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argumentERROR	 KNIME-Worker-13 RDKit Structure Normalizer	 Execute failed: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.
ERROR	 KNIME-Worker-12 RDKit Structure Normalizer	 Execute failed: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.
 ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3629867756336253650.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7087841027071702752.log
'
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option 'avareRïJQµe' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option 'avareRïJQµe' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option 'avareRïJQµe' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option 'avareRïJQµe' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option 'avareRïJQµe' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer3823432254105009706.log
'
Illegal option '' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ';' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not open log file 'C:\Users\schwama8\AppData\Local\Temp\StructureNormalizer7468780163391507691.log
'
Illegal option ')(-AÑÃQµg' with argument ''
StruCheck: Could not opERROR	 KNIME-Worker-14 RDKit Structure Normalizer	 Execute failed: Configuring the Structure Normalizer failed with error code #1 - Please check your configuration files and settings.

```

**Comment by greglandrum** [comment]
I did check in the simplified version, that's commit d480d11. The workflow looks mostly the same, but I added a row filter to go down to only one set of parameters:
image
and then changed the structure normalizer configuration so that it just uses defaults anyway.

The errors you're seeing match the kind of thing I see and are, I think, indicative of the memory problems inside the underlying structure normalization code.

**Comment by greglandrum** [comment]
But if this doesn't work for you either, then moving it over to the manual tests makes sense. I'll do that and then merge the PR later today.

**Comment by greglandrum** [comment]
That's done. Merging the PR now.

**Comment by manuelschwarze** [comment]
I just discussed with Bernd Rohde what the issue could be with the Structure Normalizer. My Java Code has not changed, his StruCheck code has not changed either. So, it must be something in the middle or how else things are called. I know that the StruCheck code has severe issues with multi-threading. For this reason there is a global Java lock to make sure that the Structure Normalizer code accesses the native StruCheck code only through one thread at a time. Bernd gave a good and valid hint: What if there is other code outside of KNIME, which also calls into StruCheck for some other feature? I would not know about this and cannot avoid it. It would lead to the same corruption problems that my global Java lock was fixing in the past - but that works only, if nobody else can get around that lock... 
I see two approaches to fix this: Either making the StruCheck code thread-safe by architectural changes and refactoring or introducing a global native lock that ensures that exactly one thread can work with StruCheck at a time. In my Java code I would need to grab in that case somehow the native lock and release it again when I am done, which requires also some Java API.

**Pull request merged**
