### PR TITLE
A couple optimizations of the diversity picker

### PR DESCRIPTION
**Pull request by greglandrum**
1. Stop using the cached version of the distance functor on the C++ side. This just slows things down and uses more memory when used with the "new" (2+ years old) diversity code.
2. Speed up the translation of KNIME bit vectors to RDKit bit vectors.

This still spends most of its time (80-90% for large datasets) translating from KNIME bit vector -> RDKit bit vector.
It's probably worth exploring how to really change this, but in the meantime we could parallelize that part of the workflow. @manuelschwarze: this is beyond my skills, but I suspect you could do that pretty quickly. Mind taking a look?

### CODE REVIEW

**Comment by manuelschwarze** [comment]
Sure, I will have a closer look. Try to squeeze it in on Friday, Nov 20, 2020.

**Comment by manuelschwarze** [comment]
@greglandrum, I did some benchmarking using an input dataset of 100'000 compounds. I also implemented multi-threading for the first part of the node processing, when it prepares all the fingerprints from the first table, either calculating them from molecules, or taking them from a fingerprint column that was just calculated before. The numbers I am getting are not as expected:

**Diversity Picker based on molecules:**
- Time before my changes: 36.6 seconds
- Single-threading, enabling again the diversity picker cache that you had disabled: 35.7 seconds => No effect
- Multi-threading with 6 threads with disabled diversity picker cache: 20.7 seconds => 40% faster - that's good

**Diversity Picker based on pre-calculated fingerprints:**
- Time before my changes: 25.6 seconds
- Single-threading, enabling again the diversity picker cache that you had disabled: 20.0 seconds => Positive effect (20% faster)
- Multi-threading with 6 threads with disabled diversity picker cache: 21.6 seconds => Only 15% faster

In both cases when watching the CPU in my Task Manager it does not go beyond 40%, which is very strange. The only explanation that comes to my mind is that there is something in the native code that would not allow full multi-threading.

The funny thing: We invested in the past in pre-calculation of fingerprints, but now with these number, using the molecules directly is actually slightly faster than using the pre-calculated fingerprints. Very strange.

Not sure, what to do with my code changes. Shall I submit them anyway? They are leading to the same results as before (verified with golden tables I took before), and have at least some benefits when using molecules directly. 

**The whole comment here is actually obsolete - I found this issue, see next comment.**

**Comment by manuelschwarze** [comment]
I was successful with performance tuning, much more than I had hoped for when writing my last comment. I profiled the code and found two culprits:

- A very bad one in the very central code that ALL RDKit nodes are using - there was a performance killer in the markForCleanup code of the RDKitCleanupTracker class: See commit 733db30
- Reducing the number of times the KNIME progress information gets updated (from every 20 rows to every 1000 rows) brings also a performance boost, it would make sense to do this in many more nodes

I brought down the times now from formerly 25 seconds to 1 second for 100'000 fingerprints and from 36 seconds to 4 seconds for 100'000 molecules (to fingerprints). :-)  

@greglandrum, feel free to merge, when you are satisfied with the code changes.

**Comment by manuelschwarze** [comment]
@greglandrum, I would recommend not to squash the commits this time when merging, but to keep them separated. That way we can easily cherry-pick the central bugfix of commit 733db30 also to other branches.

**Review by manuelschwarze — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks for those suggestions Manuel!

**Comment by greglandrum** [comment]
I really don't like having a bunch of separate commits in there for a single PR, so I did a squash merge here.
If you think it's worth doing, please go ahead and do the cherry-pick of the enhancement from your fork onto the other branches.

**Pull request merged**
